spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL Connector/J driver class
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 dialect
      hibernate:
        ddl-auto: update  # Hibernate DDL mode (update, create, validate, none)
      show-sql: true  # Show SQL queries in console